# Agenda

1. Overview of data science
2. Jupyter
3. NumPy + NumPy arrays
4. Pandas
    - Series (1-dimensional data)
    - Data frames (2-dimensional data)
    - time and Pandas
    - visualization + plots
5. Machine learning
    - Classification models
    - Regression models
    - Clustering
    - testing our models
    - a few different algorithms

In [1]:
print('Hello, out there!')  # shift + enter to execute the cell

Hello, out there!


In [2]:
x = 100   # enter == go down one line
y = 200   # shift+enter == execute the cell

In [3]:
x + y     # variables persist across cells... also, the final line of a cell, if an expression, is returned

300

# Jupyter modes

- If you click in the cell, and you have a green outline, you're in "edit mode." Typing will go into the cell. Use shift+enter to execute/finalize the cell.  You can also press [ENTER] to get the same thing.
- If you click to the left of the cell, and you have a blue outline, you're in "command mode." Typing will go to Jupyter, which will take your keystrokes as commands. You can also press [ESC] to get into command mode.

In [4]:
x * y

20000

In [5]:
x / y

0.5

# Jupyter modes

- If you click in the cell, and you have a green outline, you're in "edit mode." Typing will go into the cell. Use shift+enter to execute/finalize the cell.  You can also press [ENTER] to get the same thing.
- If you click to the left of the cell, and you have a blue outline, you're in "command mode." Typing will go to Jupyter, which will take your keystrokes as commands. You can also press [ESC] to get into command mode.

In [6]:
# Magic commands -- they all start with %

%whos

Variable   Type    Data/Info
----------------------------
x          int     100
y          int     200


In [7]:
%ls

'Cisco - 2021-12Dec-13-datascience.ipynb'


In [8]:
%pwd

'/Users/reuven/Courses/Current/Cisco-2021-12Dec-13-datascience'

In [9]:
# if you see a * between [] in the "In" of your cell, Jupyter might be
# wedged and need a kick/interrupt or even to restart.

# This is available in the Kernel menu at the top.


x + y  

300

# NumPy

NumPy provides us with an efficient array type, known as an `ndarray`, short for `n-dimensional array`. It can handle any number of dimensions, and is thus very popular in math, science, and engineering.

In [10]:
x = 0
import sys
sys.getsizeof(x)  # how many bytes does our 0 consume?

24

In [11]:
x = 10
sys.getsizeof(x)

28

In [1]:
# deprecated 
# %pylab inline   

import numpy as np   # covered by %pylab inline
from numpy import *

import matplotlib.pyplot as plt

%matplotlib inline

In [16]:
plt

<module 'matplotlib.pyplot' from '/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py'>

In [2]:
np.ndarray

numpy.ndarray

In [4]:
type(np.ndarray)  # a new data structure, a new type!

type

In [5]:
# normally, in Python, we create a new object by calling (invoking) its type
# don't do that with np.ndarray!
# rather, call np.array, and pass it an iterable (list) of numbers

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90,100])

In [6]:
# this is the repr (inherent object display) for a
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
type(a)

numpy.ndarray

In [8]:
# retrieve by index
a[0]

10

In [9]:
a[5]

60

In [10]:
a[7]

80

In [11]:
a[0:5]  # Python slice -- from 0 up to (and not including) 5

array([10, 20, 30, 40, 50])

In [12]:
# python3 -m pip install numpy

# Arrays vs. lists

Arrays have two properties:
- Their size cannot change, one they are created
- They can only contain a single data type



In [13]:
# upgrades an existing version
# pip install -U numpy 

In [14]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
# How else can we create NumPy arrays?

np.arange(5, 20)   # returns a NumPy array from 5 until (not including) 20

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5, 20, 3)  # from 5 to 20 (not included), skipping by 3

array([ 5,  8, 11, 14, 17])

In [19]:
# random integers!

np.random.seed(0)              # guarantees that random numbers will be predictable
np.random.randint(0, 100, 5)   # give me 5 random integers between 0 and 100

array([44, 47, 64, 67, 67])