# Agenda

1. Overview of data science
2. Jupyter
3. NumPy + NumPy arrays
4. Pandas
    - Series (1-dimensional data)
    - Data frames (2-dimensional data)
    - time and Pandas
    - visualization + plots
5. Machine learning
    - Classification models
    - Regression models
    - Clustering
    - testing our models
    - a few different algorithms

In [1]:
print('Hello, out there!')  # shift + enter to execute the cell

Hello, out there!


In [2]:
x = 100   # enter == go down one line
y = 200   # shift+enter == execute the cell

In [3]:
x + y     # variables persist across cells... also, the final line of a cell, if an expression, is returned

300

# Jupyter modes

- If you click in the cell, and you have a green outline, you're in "edit mode." Typing will go into the cell. Use shift+enter to execute/finalize the cell.  You can also press [ENTER] to get the same thing.
- If you click to the left of the cell, and you have a blue outline, you're in "command mode." Typing will go to Jupyter, which will take your keystrokes as commands. You can also press [ESC] to get into command mode.

In [4]:
x * y

20000

In [5]:
x / y

0.5

# Jupyter modes

- If you click in the cell, and you have a green outline, you're in "edit mode." Typing will go into the cell. Use shift+enter to execute/finalize the cell.  You can also press [ENTER] to get the same thing.
- If you click to the left of the cell, and you have a blue outline, you're in "command mode." Typing will go to Jupyter, which will take your keystrokes as commands. You can also press [ESC] to get into command mode.

In [6]:
# Magic commands -- they all start with %

%whos

Variable   Type    Data/Info
----------------------------
x          int     100
y          int     200


In [7]:
%ls

'Cisco - 2021-12Dec-13-datascience.ipynb'


In [8]:
%pwd

'/Users/reuven/Courses/Current/Cisco-2021-12Dec-13-datascience'

In [9]:
# if you see a * between [] in the "In" of your cell, Jupyter might be
# wedged and need a kick/interrupt or even to restart.

# This is available in the Kernel menu at the top.


x + y  

300

# NumPy

NumPy provides us with an efficient array type, known as an `ndarray`, short for `n-dimensional array`. It can handle any number of dimensions, and is thus very popular in math, science, and engineering.

In [10]:
x = 0
import sys
sys.getsizeof(x)  # how many bytes does our 0 consume?

24

In [11]:
x = 10
sys.getsizeof(x)

28

In [1]:
# deprecated 
# %pylab inline   

import numpy as np   # covered by %pylab inline
from numpy import *

import matplotlib.pyplot as plt

%matplotlib inline

In [16]:
plt

<module 'matplotlib.pyplot' from '/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py'>

In [2]:
np.ndarray

numpy.ndarray

In [4]:
type(np.ndarray)  # a new data structure, a new type!

type

In [5]:
# normally, in Python, we create a new object by calling (invoking) its type
# don't do that with np.ndarray!
# rather, call np.array, and pass it an iterable (list) of numbers

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90,100])

In [6]:
# this is the repr (inherent object display) for a
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
type(a)

numpy.ndarray

In [8]:
# retrieve by index
a[0]

10

In [9]:
a[5]

60

In [10]:
a[7]

80

In [11]:
a[0:5]  # Python slice -- from 0 up to (and not including) 5

array([10, 20, 30, 40, 50])

In [12]:
# python3 -m pip install numpy

# Arrays vs. lists

Arrays have two properties:
- Their size cannot change, one they are created
- They can only contain a single data type



In [13]:
# upgrades an existing version
# pip install -U numpy 

In [14]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
# How else can we create NumPy arrays?

np.arange(5, 20)   # returns a NumPy array from 5 until (not including) 20

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5, 20, 3)  # from 5 to 20 (not included), skipping by 3

array([ 5,  8, 11, 14, 17])

In [24]:
# random integers!

np.random.seed(0)              # guarantees that random numbers will be predictable
np.random.randint(0, 100, 5)   # give me 5 random integers between 0 and 100

array([44, 47, 64, 67, 67])

In [25]:
# random floats

np.random.rand(5)  # returns 5 numbers between 0 and 100

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298])

In [26]:
# NumPy arrays are mutable -- we *can* change them.  We cannot the length, but we can change the content
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
# indexing is 0 based, just like in Python

a[3] = 70
a[5] = 25


In [28]:
a

array([ 10,  20,  30,  70,  50,  25,  70,  80,  90, 100])

In [30]:
# help(np.random)

# Exercises: Simple NumPy manipulations

1. Create a NumPy array with three elements -- the integers from your birthday! It should contain the year, month, and day (all in numbers).
2. Retrieve the year.
3. Replace the year with the current year, and print the array.
4. Create a NumPy array with every 3rd number from 567 to 890. What is the 8th number (i.e., at index 7) in this array? 

In [31]:
# pip install -U matplotlib 

In [32]:
a = np.array([1970, 7, 14])

a[0]

1970

In [33]:
a[0] = 2021
a

array([2021,    7,   14])

In [35]:
a = np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [36]:
a[7]

588

In [37]:
# Python list!
mylist = [10, 20, 30]

mylist + mylist  # add two lists together

[10, 20, 30, 10, 20, 30]

In [38]:
mylist + 4

TypeError: can only concatenate list (not "int") to list

In [41]:
# NumPy array!
a = np.array([10, 20, 30])
a + a                      # all operations on an array are vectorized

array([20, 40, 60])

In [42]:
a + np.array([2,4,6,8,10])

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [43]:
a

array([10, 20, 30])

In [44]:
a + 4 # broadcasting -- vector + scalar can have operations run on them, the scalar is used with each element

array([14, 24, 34])

In [45]:
a

array([10, 20, 30])

In [46]:
# some basic methods for working with NumPy arrays

a = np.array([10, 20, 30, 35, 15, -8, 20, 50])

a.mean()

21.5

In [47]:
a.sum()  

172

In [50]:
a.size  # this is not a method!

8

In [51]:
a.sum() / a.size

21.5

In [52]:
a.std()   # standard deviation -- how much do the values vary from the mean?

16.263455967290593

In [53]:
a.min()

-8

In [54]:
a.max()

50

In [56]:
np.random.rand(5)  # 5 numbers between 0 and 1

array([0.27265629, 0.47766512, 0.81216873, 0.47997717, 0.3927848 ])

In [57]:
np.random.rand(5) * 100    # 5 numbers between 0 and 100

array([83.60787635, 33.73961604, 64.81718721, 36.82415398, 95.7155159 ])

In [58]:
# another method: np.ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
# also: np.zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Exercise: Temperatures + more

1. Look up the 10-day forecast for wherever you live.
2. Create a 10-element NumPy array with the predicted high temperatures.
3. Find the mean and standard deviation of those.
4. Create a 20-element NumPy array of random ints between 0 and 100.  What is the mean?  Do you expect the mean to change if you have 200 elements?  How should it change?  How about 2,000 elements?

In [62]:
a = np.array([23, 22, 18, 17, 16, 15, 17, 18, 17, 16])
a.mean()


17.9

In [63]:
a.std()

2.467792535850613

In [64]:
a = np.random.randint(0, 100, 20)
a.mean()

47.55

In [66]:
a = np.random.randint(0, 100, 2000)
a.mean()

49.5745

In [67]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [69]:
# Indexing

a = np.array([23, 22, 18, 17, 16, 15, 17, 18, 17, 16])
a

array([23, 22, 18, 17, 16, 15, 17, 18, 17, 16])

In [70]:
a[0]

23

In [71]:
a[1]

22

In [72]:
# fancy indexing
a[[0, 1]]   # give me an array back with the elements of a at both 0 and 1

array([23, 22])

In [73]:
a[[2, 4,6, 2,4,6]]

array([18, 16, 17, 18, 16, 17])

In [74]:
# boolean indexing

a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [77]:
# use booleans (True/False) as elements of our selection index!
# note: if we do this, we must have the same number of booleans as elements in a

# "boolean index" or a "mask index"
a[[True, False, True, False]]    # only get the elements back that match True

array([10, 30])

In [78]:
a[[True, True, True, True]]

array([10, 20, 30, 40])

In [79]:
a[[False, False, False, False]]

array([], dtype=int64)

In [80]:
# remember that all operators are vectorized
# if we use a array and a scalar, then the operation is broadcast

a + 5

array([15, 25, 35, 45])

In [81]:
a > 20

array([False, False,  True,  True])

In [83]:
# first: create a boolean array by comparing a>20
# then: apply that boolean array as a boolean index on a 
# thus: get all of the elements of a that are > 20

a[a>20]

array([30, 40])

In [84]:
# Resume at :50

In [85]:
a

array([10, 20, 30, 40])

In [87]:
# always think about the [] as saying, "Where this is the case"
a[a == 30]

array([30])

In [88]:
# show me all elements of a that are greater than the mean
a[a>a.mean()]

array([30, 40])

In [89]:
a = np.array([10, 15, 20, 25, 30])

a

array([10, 15, 20, 25, 30])

In [90]:
# I want to find all of the odd elements
a%2

array([0, 1, 0, 1, 0])

In [92]:
# let's get the odd values!

# this doesn't work the way we expect because we're getting
# integers (and thus a fancy index with elements at indexes 0 and 1)

# we are *not* getting True and False values, which would return
# only those elements that are odd.
a[a%2]

array([10, 15, 10, 15, 10])

In [93]:
# how can/should we do it?
a[a%2==1]

array([15, 25])

In [94]:
# get the even elements
a[a%2==0]

array([10, 20, 30])

# Exercises: Boolean indexes

1. Create an array of 20 random integers from 0 - 100.
2. Find the largest even number.
3. Find the mean of the odd numbers.
4. Create an array of 20 floats from 0 - 1,000.
5. Find the items that are less than the mean.
6. Find the items that are less than the mean-std.